name: Scrape 63
on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *"
jobs:
  actions_63:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute python script
        run: python main.py ./data/txt/county_list_63.txt
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin git@github.com:ishan9299/zillow-scraper.git

          # Pull latest changes
          # Add and commit changes
          echo "git commit"
          git add .
          git commit -m "Automated scrape for file 63 - $(date +%F)"

          echo "git pull"
          git config pull.rebase true
          git pull origin

          echo "git push"
          git push origin master