name: Scrape 41
on:
  workflow_dispatch:
  schedule:
    - cron: "10 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute python script
        run: python main.py ./data/txt/county_list_41.txt
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: git pull files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git pull origin master --rebase
      - name: git commit files
        run: |
          git add .
          git status
          if ! git diff --staged --quiet; then
            git commit -m "Automated scrape for file 41" || echo "Nothing to commit"
            git push origin master || echo "Push failed"
          else
            echo "No changes to commit"
          fi