name: Merge CSVs

on:
  push:
    branches:
      - master

jobs:
  final-job:
    needs: [actions_0, actions_1, actions_2, actions_3, actions_4, actions_5, actions_6, actions_7, actions_8, actions_9, actions_10, actions_11, actions_12, actions_13, actions_14, actions_15, actions_16, actions_17, actions_18, actions_19, actions_20, actions_21, actions_22, actions_23, actions_24, actions_25, actions_26, actions_27, actions_28, actions_29, actions_30, actions_31, actions_32, actions_33, actions_34, actions_35, actions_36, actions_37, actions_38, actions_39, actions_40, actions_41, actions_42, actions_43, actions_44, actions_45, actions_46, actions_47, actions_48, actions_49, actions_50, actions_51, actions_52, actions_53, actions_54, actions_55, actions_56, actions_57, actions_58, actions_59, actions_60, actions_61, actions_62, actions_63, actions_64, actions_65, actions_66, actions_67, actions_68, actions_69, actions_70, actions_71, actions_72, actions_73, actions_74, actions_75, actions_76, actions_77, actions_78, actions_79, actions_80, actions_81, actions_82, actions_83, actions_84, actions_85, actions_86, actions_87, actions_88, actions_89, actions_90, actions_91, actions_92, actions_93, actions_94, actions_95, actions_96, actions_97, actions_98, actions_99, actions_100, actions_101, actions_102, actions_103, actions_104, actions_105, actions_106, actions_107, actions_108, actions_109, actions_110, actions_111, actions_112, actions_113, actions_114, actions_115, actions_116, actions_117, actions_118, actions_119, actions_120, actions_121, actions_122, actions_123, actions_124, actions_125, actions_126, actions_127, actions_128, actions_129, actions_130, actions_131, actions_132, actions_133, actions_134, actions_135, actions_136, actions_137, actions_138, actions_139, actions_140, actions_141, actions_142, actions_143, actions_144, actions_145, actions_146, actions_147, actions_148, actions_149, actions_150, actions_151, actions_152, actions_153, actions_154, actions_155, actions_156, actions_157, actions_158, actions_159, actions_160, actions_161, actions_162, actions_163, actions_164, actions_165, actions_166, actions_167, actions_168, actions_169, actions_170, actions_171, actions_172, actions_173, actions_174, actions_175, actions_176, actions_177, actions_178, actions_179, actions_180, actions_181, actions_182, actions_183, actions_184, actions_185, actions_186, actions_187, actions_188, actions_189, actions_190, actions_191, actions_192, actions_193, actions_194, actions_195, actions_196, actions_197, actions_198, actions_199, actions_200, actions_201, actions_202, actions_203, actions_204, actions_205, actions_206, actions_207, actions_208, actions_209, actions_210, actions_211, actions_212, actions_213, actions_214, actions_215, actions_216, actions_217, actions_218, actions_219, actions_220, actions_221, actions_222, actions_223, actions_224, actions_225, actions_226, actions_227, actions_228, actions_229, actions_230, actions_231, actions_232, actions_233, actions_234, actions_235, actions_236, actions_237, actions_238, actions_239, actions_240, actions_241, actions_242, actions_243, actions_244, actions_245, actions_246, actions_247, actions_248, actions_249, actions_250, actions_251, actions_252, actions_253, actions_254, actions_255, actions_256]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: execute python script
        run: python merge_csvs.py

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${ secrets.DEPLOY_KEY }" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin git@github.com:ishan9299/zillow-scraper.git

          echo "git commit"
          git add .
          git commit -m "Automated scrape for file 0 - $(date +%F)"

          echo "git pull"
          git config pull.rebase true
          git pull origin

          echo "git push"
          git push origin master
